// Word banks (uppercase). Answers contain only complete words (length 5-7).
const ANSWERS = [
  // 5-letter answers (jazz names/terms and common words)
  "MILES","DAVIS","SONNY","BASIE","HINES","OSCAR","LOUIS","MCCOY","DIZZY","SCOTT",
  "BEBOP","SWING","PIANO","BLUES","TUNES","SOLOS","LYRIC","SCATS","BRASS","NOTES", "DRUMS", "BARRY", "TENOR", "CHORD"
  "BROWN", "MISTY", "BOSSA", "VOCAL", "HORNS", "SAXES", "FUNKY", "SMOKE", 
  

  // 6-letter answers
  "PARKER","MELODY","RHYTHM","GROOVE","IMPROV","GARDEN","NUMBER",
  "PEOPLE","ORANGE","PURPLE","JAZZED","SEPTET", "POTATO", "GUITAR", "MELODY", "REDMAN", "MINGUS", 
  "FREDDY", "CLARKE", "GILLES", "CYMBAL", "FUSION"

  // 7-letter answers
  "BRUBECK","TRUMPET","SEPTETS","QUARTET","HARMONY","ANIMALS","COUNTRY","NUMBERS",
  "FRIENDS","GARDENS","PLANETS","RESULTS", "SEVENTH", "UPRIGHT", "CHANGES", "MOMENTS", "BASSIST"
];

// Expanded allowed guesses (includes many non-jazz common words to help players).
// This list is larger (roughly 4x the answer bank) and contains many common 5-7 letter words.
const ALLOWED = Array.from(new Set([
  ...ANSWERS,
  "ABOUT","OTHER","WHICH","THEIR","THERE","FIRST","WOULD","THESE","CLICK","LIGHT",
  "RIGHT","THINK","WHERE","WHILE","AFTER","AGAIN","BELOW","UNDER","POWER","SOUND",
  "HEART","NIGHT","RIVER","RIVERS","FOREST","FLOWER","FAMILY","PEOPLE","ANSWER","PUZZLE",
  "GUESS","SECRET","MUSIC","SINGER","PLAYER","GUITAR","DRUMMER","BASSIST","PIANIST","VIOLIN",
  "CELLO","BRIDGE","STUDIO","RECORD","ALBUMS","SESSION","LEGEND","SWINGS","TABLES","CHAIRS",
  "STAGE","VENUES","CITIES","URBAN","NIGHTLY","SUNDAY","MONDAY","FRIDAY","SMOOTH","COOLER",
  "HOTTER","THREE","SEVEN","EIGHT","DANCE","GROOVE","LISTEN","SUMMER","AUTUMN","WINTER",
  "SPRING","LONDON","PARIS","TOKYO","MILANO","BROOKLYN","HARLEM","STORMY","RAINY","JAZZES",
  "SWEETS","PIZZA","COFFEE","BAKERY","SUGAR","HONEY","PLANTS","ORCHID","GARDEN","FLOWER",
  "WINDOW","DOORS","STAGES","BISTRO","TUNING","METRON","RHYTHM","MELODY","SERENE","COZYING",
  "RELAXE","BREEZY","MELLOW","BRIGHT","SHINER","BOLDLY","ROMANT","CLASSY","ELEGAN","SOFTER",
  "DAPPER","DAPPER","SMILES","LAUGHS","POCKET","POETRY","LYRICZ","VERSEZ","CHORUS","BRIDGE",
  "SOULSE","TEMPO1","TEMPOS","BEATING","DRIFTS","FLOATS","SWAYED","SWAYIN","SILENT","HUSHED",
  "MIDNIT","MIDNTS","CANDLE","SHADOW","TWILIT","TWILIG","MOONLY","MOONBE","STARRY","STARSY",
  "STROLL","WALKER","WANDER","TRAVEL","FLIGHT","TAKEOFF","LANDED","ARRIVE","DEPART","VOYAGE",
  "ANCHOR","DOCKED","MARINA","HARBOUR","SEASIDE","COASTS","BREEZE","TROPIC","ISLAND","PARADX",
  "ORIGINAL","COMMON","SIMPLE","SIMPLE","UNIQUE","RANDOM","SERIES","GLOBAL","LOCAL","NATIVE",
  "BRIDGE","CIRCLE","SQUARE","POLISH","GLOSSY","MATTEY","TEXTUR","LAYOUT","CENTER","FRAMED",
  "COYOTE","RABBIT","SQUIR","BIRDIE","SPARROW","ROOSTR","NATURE","PLANET","GALAXY","COSMIC",
  "ASTERO","COMETS","ORBITA","ROTATE","GRAVIT","WEIGHT","VOLUME","SENSOR","DEVICE","REMOTE",
  "ONLINE","OFFLINE","SERVER","CLIENT","BINARY","STRING","NUMBER","DIGITS","VECTOR","MATRIX",
  "PLUGIN","MODULE","PACKAGE","NATIVE","BINARY","SOURCE","OUTPUT","INPUTS","EDITOR","CODING",
  "DEVELO","ENGINE","BROWSER","MOBILE","DESKTOP","TABLET","WINDOW","SCREEN","LAYERS","ELEMENT",
  "BUTTON","TOGGLE","SLIDER","RADIO","CHECKX","LABELS","PANELS","WIDGET","THEMES","DARKER",
  "LIGHTS","SHADOW","FILTER","TUNING","TUNERS","TUNING","SOUNDS","NOTIFY","ALERTS","REMINDR",
  "SIMPLE","DOUBLE","TRIPLE","SINGLE","STRING","NUMBER","MODULE","IMPORTS","EXPORTS","RETURNZ",
  "ACTION","TARGET","SOURCE","BRANCH","MERGED","COMMIT","PUSHES","PULLER","REMOTE","ORIGIN",
  "STABLE","BETA01","RELEASE","VERSION","CHANGE","UPDATE","UPLOAD","DOWNLOAD","INSTALL","UNPACK",
  "ARCHIV","BACKUP","RECOVE","RESTOR","FILTER","SEARCH","FINDER","GOOGLE","BINGED","DUCKDUK",
  "YOUTUBE","SPOTFY","APPLEM","AMAZON","MICROS","LINUXS","UBUNTU","DEBIAN","FEDORA","CENTOS"
]));

window.JAZZ_ANSWERS = ANSWERS;
window.JAZZ_ALLOWED = ALLOWED;
